#!/bin/sh

echo "Downloading Alpine Linux"
wget https://dl-cdn.alpinelinux.org/alpine/v3.21/releases/x86_64/alpine-minirootfs-3.21.3-x86_64.tar.gz
echo "Unpacking"
tar xvf ./alpine-minirootfs-3.21.3-x86_64.tar.gz
echo "OK"
